language: python
python:
    - "2.7"
install:
    # Install miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - bash Miniconda-latest-Linux-x86_64.sh -b
    - export CONDA_ROOT=~/miniconda
    - export PATH=${CONDA_ROOT}/bin:$PATH

    # Create and activate an environment to test with
    - export TEST_ENV_NAME=test-env
    - conda create -y -n ${TEST_ENV_NAME} -c ilastik ilastik-deps-pc-headless
    - source ${CONDA_ROOT}/bin/activate ${TEST_ENV_NAME}
    - export TEST_ENV_PREFIX=${CONDA_ROOT}/envs/TEST_ENV_NAME

    ## Replace packaged source with full git repo
    #- rm -rf ${TEST_ENV_PREFIX}/ilastik-meta
    #- git clone http://github.com/ilastik/ilastik-meta ${TEST_ENV_PREFIX}/ilastik-meta
    #- cd ${TEST_ENV_PREFIX}/ilastik-meta
    #- git submodule init
    #- git submodule update --recursive
    #- git submodule foreach "git checkout master"
script:
   - nosetests --nologcapture --ignore-files=testInterpolatedFeatures.py tests
notifications:
  email:
    - bergs@janelia.hhmi.org
branches:
  only:
    - master
