clone_folder: c:\projects\ilastik

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda36-x64


install:
  - CALL %MINICONDA%/Scripts/activate.bat
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q --yes -n %ENV_NAME% -c ilastik-forge/label/staging -c conda-forge ilastik-dependencies-no-solvers
  # Remove the conda ilastik-meta
  - conda remove ilastik-meta
  - activate %ENV_NAME%
  - cd \
  # Get the current master of all submodules
  - git clone https://github.com/ilastik/ilastik-meta c:\ilastik\ilastik-meta
  - cd ilastik\ilastik-meta
  - git submodule update --init --recursive
  - git submodule foreach "git checkout master"
  - ps: rm -Force -Recurse c:\ilastik\ilastik-meta\ilastik\
  # replace with whatever version of ilastik triggered the appveyor
  - ps: cp -recurse C:\projects\ilastik c:\ilastik\ilastik-meta\ilastik
  # Point to the current ilastik-meta
  - set ILASTIK_PTH=%MINICONDA%/envs/%ENV_NAME%/Lib/site-packages/ilastik-meta.pth
  - echo C:/ilastik/ilastik-meta/lazyflow > %ILASTIK_PTH%
  - echo C:/ilastik/ilastik-meta/volumina >> %ILASTIK_PTH%
  - echo C:/ilastik/ilastik-meta/ilastik >> %ILASTIK_PTH%

build: off

test_script:
  - CALL %MINICONDA%/Scripts/activate.bat
  - activate %ENV_NAME%
  - cd \
  - cd ilastik\ilastik-meta\ilastik\tests
  - pytest --run-legacy-gui

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
