image: Visual Studio 2019

clone_folder: c:\projects\ilastik

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda38-x64
  IlASTIK_ROOT: C:\ilastik
  VOLUMINA_SHOW_3D_WIDGET: 0
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -xr!*/ -ir-!*.tar.bz2 -ir-!*.conda  # Exclude directories only cache downloaded tars

cache:
  - C:\Miniconda38-x64\pkgs -> appveyor.yml

install:
  - cmd: set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: where conda
  - cmd: conda config --set always_yes yes --set changeps1 no --set channel_priority strict
  - cmd: conda update -n base -c conda-forge --all
  - cmd: conda install -n base -c conda-forge mamba conda-build boa setuptools_scm
  - |
    mamba env create --name %ENV_NAME% --file dev\environment-dev.yml
    mamba install --name %ENV_NAME% --freeze-installed -c ilastik-forge -c conda-forge volumina
    mamba run -n %ENV_NAME% pip install -e .
  - mamba clean -p

build: off

test_script:
  - cmd: CALL activate %ENV_NAME%
  - cmd: set VOLUMINA_SHOW_3D_WIDGET=0
  - cmd: pytest --run-legacy-gui

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))