channels:
  - ilastik-forge/label/experimental
  - local
  - ilastik-forge
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python 3.8.*
  - numpy 1.21.*
  - appdirs
  - cachetools
  - dpct
  - fastfilters
  - future
  - greenlet
  - grpcio
  - h5py
  - hytra
  - ilastik-feature-selection
  - ilastikrag
  - ilastiktools
  - jsonschema
  - mamutexport
  - marching_cubes
  - ndstructs
  - nifty
  - psutil
  - pyopengl
  - pyqt 5.15.*
  - pyqtgraph
  - python-elf
  # - pytiff
  - qimage2ndarray
  - scikit-image
  - scikit-learn
  # see note in conda recipe about tifffile compatibility
  - tifffile
  # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
  # need to bump this manually until there is a true version bump in vigra
  # _1033 - last build with boost 1.74
  - vigra 1.11.1=*_1033
  - wsdt
  - xarray
  - z5py

  # Neural Network Workflow dependencies
  # can be changed to request gpu versions
  # - pytorch 1.9.* *cpu*
  - pytorch 1.13.*

  # - cpuonly
  # - pytorch 1.9.*=*cu*
  # - cudatoolkit 11.1.*
  # - tensorflow 1.14.*
  - tiktorch >=22.7.1*

  # dev-only dependencies
  - conda-build
  - mypy
  - pre-commit
  - pytest
  - pytest-qt

  # ensure working environment on apple M1 via rosetta
  # remove once native builds are available
  #- mkl 2021.*  # [osx and x86_64]
