channels:
  - ilastik-forge
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python 3.9.*
  - numpy 1.21.*
  - appdirs
  - cachetools
  - dpct
  - fastfilters
  - future
  - greenlet
  - grpcio
  - h5py
  - hytra
  - ilastik-feature-selection
  - ilastikrag
  - ilastiktools
  - jsonschema
  - mamutexport
  - marching_cubes
  - ndstructs
  - nifty
  # need to update our packages to be compatible with pandas 2 API
  - pandas <2
  - psutil
  - pyopengl
  - pyqt 5.12.*
  - pyqtgraph
  - python-elf
  - pytiff
  - qimage2ndarray
  - scikit-image
  - scikit-learn
  # see note in conda recipe about tifffile compatibility
  - tifffile
  # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
  # need to bump this manually until there is a true version bump in vigra
  - vigra 1.11.1=*_1033
  - xarray
  - z5py

  # Neural Network Workflow dependencies
  # can be changed to request gpu versions
  - pytorch 1.13.* *cpu*

  - cpuonly
  # - pytorch 1.9.*=*cu*
  # - cudatoolkit 11.1.*
  - tiktorch >=23.2.0

  # dev-only dependencies
  - conda-build
  - mypy
  - pre-commit
  - pytest >4
  - pytest-qt

  # ensure working environment on apple M1 via rosetta
  # remove once native builds are available
  # - mkl 2021.*  # [osx]
