version: 2.1
jobs:
  checkout_ilastik:
    working_directory: /root/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      ILASTIK_ROOT: /root/ilastik
    docker:
    - image: continuumio/miniconda3
    steps:
    - checkout
    - run:
        name: initialize ilastik-meta, link to code
        command: >
            git clone https://github.com/ilastik/ilastik-meta ${ILASTIK_ROOT}/ilastik-meta &&
            cd ${ILASTIK_ROOT}/ilastik-meta &&
            git submodule init &&
            git submodule update --recursive &&
            git submodule foreach "git checkout main" &&
            rm -rf ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
            ln -s ${ILASTIK_ROOT}/ilastik ${ILASTIK_ROOT}/ilastik-meta/ilastik
    - save_cache:
        name: store repo cache
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /root/ilastik

  test:
    working_directory: /root/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      ILASTIK_ROOT: /root/ilastik
      ON_CIRCLE_CI: 1
      TEST_ENV_NAME: test-env
      VOLUMINA_SHOW_3D_WIDGET: 0
    docker:
    - image: continuumio/miniconda3
    steps:
    - restore_cache:
        name: restoring dependency cache
        keys:
        # This branch if available
        - v1.4.12-dep-{{ .Branch }}-{{ epoch }}
        # Default branch if not
        - v1.4.12-dep-main-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1.4.12-dep-
    - restore_cache:
        name: restore ilastik-repo cache
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: update conda
        command: >
            conda config --set always_yes yes --set changeps1 no --set channel_priority strict &&
            conda update -q conda -c conda-forge &&
            conda install -n base -c conda-forge conda-build mamba
    - run:
        name: install apt dependencies
        command: >
            apt-get update &&
            apt-get install -yy libgl1-mesa-dev xvfb curl
    - run:
        name: create ilastik conda environment
        command: >
            cd ${ILASTIK_ROOT}/ilastik-meta &&
            mamba env create --name ${TEST_ENV_NAME} --file ilastik/dev/environment-dev.yml &&
            mamba install --name ${TEST_ENV_NAME} --freeze-installed -c ilastik-forge -c conda-forge mpi4py pytest-cov volumina &&
            conda run -n ${TEST_ENV_NAME} pip install -e ilastik

    - run:
        name: run ilastik tests
        command: >
            conda activate ${TEST_ENV_NAME} &&
            cd ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
            mkdir test-results &&
            xvfb-run --server-args="-screen 0 1024x768x24" pytest --cov-report=xml --cov=lazyflow --cov=ilastik --run-legacy-gui --junitxml=test-results/junit.xml &&
            bash <(curl -s https://codecov.io/bash)
    - store_test_results:
        path: test-results
    - save_cache:
        name: store dependency cache
        key: v1.4.12-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - /opt/conda/pkgs


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_ilastik
      - test:
          requires:
            - checkout_ilastik
