version: 2
## Customize the test machine
jobs:
  build:
    working_directory: ~/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CONDA_ROOT: /home/circleci/miniconda
      TEST_ENV_NAME: test-env
      ILASTIK_ROOT: /home/circleci/ilastik
      VOLUMINA_SHOW_3D_WIDGET: 0
      ON_CIRCLE_CI: 1
    docker:
    - image: continuumio/miniconda3
    steps:
    - checkout
    - restore_cache:
        keys:
        # This branch if available
        - v1.4.10-dep-{{ .Branch }}-
        # Default branch if not
        - v1.4.10-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1.4.10-dep-
    - run: >
        conda config --set always_yes yes --set changeps1 no --set channel_priority strict &&
        conda update -q conda &&
        conda install -n base -c conda-forge conda-build
    - run: git clone http://github.com/ilastik/ilastik-meta ${ILASTIK_ROOT}/ilastik-meta
    - run: >
        cd ${ILASTIK_ROOT}/ilastik-meta &&
        git submodule init &&
        git submodule update --recursive &&
        git submodule foreach "git checkout master"
    - run: >
        rm -rf ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
        ln -s `pwd` ${ILASTIK_ROOT}/ilastik-meta/ilastik
    - run: >
        sudo apt-get update &&
        sudo apt-get install -yy libgl1-mesa-dev xvfb &&
        conda activate base &&
        cd ${ILASTIK_ROOT}/ilastik-meta &&
        python ilastik/scripts/devenv.py create -n ${TEST_ENV_NAME}
        -p pytest-qt ilastik-dependencies-no-solvers black
        -c ilastik-forge conda-forge defaults
    # Save dependency cache
    - save_cache:
        key: v1.4.10-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - /opt/conda/pkgs
    # Test
    - run: >
        conda activate ${TEST_ENV_NAME} &&
        cd ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
        mkdir test-results &&
        xvfb-run --server-args="-screen 0 1024x768x24" pytest --run-legacy-gui --junitxml=test-results/junit.xml
    - run: >
        conda activate ${TEST_ENV_NAME} &&
        cd ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
        git diff --name-only --diff-filter=AM master.. |
            grep ".*\.py" |
            xargs black --check --line-length=120

    - store_test_results:
        path: test-results
