version: 2

jobs:

  checkout_ilastik:
    working_directory: /root/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      ILASTIK_ROOT: /root/ilastik
    docker:
    - image: continuumio/miniconda3
    steps:
    - checkout
    - run:
        name: initialize ilastik-meta, link to code
        command: >
            git clone https://github.com/ilastik/ilastik-meta ${ILASTIK_ROOT}/ilastik-meta && 
            cd ${ILASTIK_ROOT}/ilastik-meta &&
            git submodule init &&
            git submodule update --recursive &&
            git submodule foreach "git checkout master" &&
            rm -rf ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
            ln -s ${ILASTIK_ROOT}/ilastik ${ILASTIK_ROOT}/ilastik-meta/ilastik
    - save_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /root/ilastik

  build:
    working_directory: ~/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      ILASTIK_ROOT: /root/ilastik
      ON_CIRCLE_CI: 1
      TEST_ENV_NAME: test-env
      VOLUMINA_SHOW_3D_WIDGET: 0
    docker:
    - image: continuumio/miniconda3
    steps:
    - restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
    - restore_cache:
        keys:
        # This branch if available
        - v1.4.10-dep-{{ .Branch }}-
        # Default branch if not
        - v1.4.10-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1.4.10-dep-
    - run: >
        conda config --set always_yes yes --set changeps1 no --set channel_priority strict &&
        conda update -q conda &&
        conda install -n base -c conda-forge conda-build
    - run: >
        sudo apt-get update &&
        sudo apt-get install -yy libgl1-mesa-dev xvfb &&
        conda activate base &&
        cd ${ILASTIK_ROOT}/ilastik-meta &&
        python ilastik/scripts/devenv.py create -n ${TEST_ENV_NAME}
        -p pytest-qt ilastik-dependencies-no-solvers black
        -c ilastik-forge conda-forge defaults
    # Save dependency cache
    - save_cache:
        key: v1.4.10-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - /opt/conda/pkgs
    # Test
    - run: >
        conda activate ${TEST_ENV_NAME} &&
        cd ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
        mkdir test-results &&
        xvfb-run --server-args="-screen 0 1024x768x24" pytest --run-legacy-gui --junitxml=test-results/junit.xml
    - run: >
        conda activate ${TEST_ENV_NAME} &&
        cd ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
        git diff --name-only --diff-filter=AM master.. |
            grep ".*\.py" |
            xargs black --check --line-length=120

    - store_test_results:
        path: test-results


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_ilastik
      - build:
          requires:
            - checkout_ilastik
