{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: ilastik-core
  version: {{ setup_py_data.version }}

source:
  path: ..

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=40.0
    - setuptools_scm
  run:
    - python >=3.7
    - numpy >1.12
    - appdirs
    - cachetools
    - dpct
    - fastfilters
    - future
    - greenlet
    - grpcio
    - h5py
    - hytra
    - ilastik-feature-selection
    - ilastikrag
    - ilastiktools
    - jsonschema
    - mamutexport
    - marching_cubes
    - ndstructs
    - nifty
    - psutil
    - pyopengl
    - pyqt >=5.12
    - python-elf
    - pytiff
    - scikit-image
    - scikit-learn
    # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
    # need to bump this manually until there is a true version bump in vigra
    - vigra 1.11.1=*_1028
    - wsdt
    - xarray
    - z5py


build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ setup_py_data.version }}
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


test:
  imports:
    - ilastik
    - ilastik.experimental
    - ilastik.config
    - ilastik.applets
    - ilastik.workflows
    - lazyflow

  source_files:
    - tests
    - pytest.ini

  requires:
    - pytest >=3,<4
    - pytest-qt
    - volumina
    - tiktorch

  commands:
    - pytest -v .
