{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: ilastik-package-meta-recipe
  version: {{ setup_py_data.version }}

source:
  path: ..


outputs:
  - name: ilastik-core

    build:
      number: 0
      noarch: python
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ setup_py_data.version }}
      script:
        - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    requirements:
      host:
        - python 3.9
        - pip
        - setuptools >=40.0
        - setuptools_scm
      run:
        - python 3.9*
        - numpy >1.20
        - appdirs
        - cachetools
        - dpct
        - fastfilters
        - future
        - greenlet
        - grpcio 1.41*
        - h5py
        - hytra
        - ilastik-feature-selection
        - ilastikrag
        - ilastiktools
        - jsonschema
        - mamutexport
        - marching_cubes
        - ndstructs
        - nifty
        # need to update our packages to be compatible with pandas 2 API
        - pandas <2
        - psutil
        - pyopengl
        - pyqt 5.15.*
        - python-elf
        - scikit-image
        - scikit-learn
        # tiffile >2020.9.22,<=2021.11.2  # [py37]
        - tifffile
        # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
        # need to bump this manually until there is a true version bump in vigra
        - vigra 1.11.1=*_1033
        - xarray
        - z5py
      run_constrained:
        - tiktorch >=23.5.0
        - volumina >=1.3.9

    test:
      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow

      source_files:
        - tests
        - pytest.ini

      requires:
        - numpy 1.21.*
        - pytest >4
        - pytest-qt
        - volumina
        - tiktorch

      commands:
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik-core package enables ilastik-api usage to mix into environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
        

  - name: ilastik
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.9.*
        - ilastik-core {{ setup_py_data.version }}
        - pytorch >=1.6
        - tiktorch 23.5.0*
        - numpy 1.21.*
        - inferno
        - torchvision
        - volumina

    test:
      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >4
        - pytest-qt
        # need to help mamba here a bit
        # - ilastik-pytorch-version-helper-cpu
        - pytorch 1.13.*

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch

      commands:
        - ilastik --help
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
