name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-w-conda-recipe:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
      - name: install xvfb/deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -yy libgl1-mesa-dev xvfb curl
      - name: linux conda build test
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          conda install -n base -c conda-forge conda-build setuptools_scm -y
          xvfb-run conda build -c ilastik-forge/label/freepy -c conda-forge conda-recipe
      - name: osx conda build test
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: |
          conda install -n base -c conda-forge conda-build setuptools_scm -y
          conda build -c ilastik-forge/label/freepy -c conda-forge conda-recipe
      - name: windows conda-build test
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        # auto activation of env does not seem to work on win
        run: |
          conda install -n base -c conda-forge conda-build  setuptools_scm -y & conda build -c ilastik-forge/label/freepy -c conda-forge conda-recipe
