name: static-code-analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: akaihola/darker@1.5.1
        with:
          options: "--check --diff --revision=origin/main..."
          src: "."
          # due to incompatibility of black with the current release of the
          # darker github action, we need to use a non-release version
          # ref: https://github.com/ilastik/ilastik/issues/2640
          version: "@3c675b009d747cadd6e8048d2c57a5b1cd54fb3e"
